change in deploy backend

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,21 +46,30 @@ jobs:
             cp -r dist/* /var/www/koyal/
 
             echo "📦 Installing backend"
+    
             cd ../Server
-            npm install
 
+            npm install
+            echo "🔍 Checking if PM2 is installed"
+            if ! command -v pm2 &> /dev/null
+            then
+                echo "🛠 PM2 not found. Installing PM2 globally..."
+                npm install -g pm2
+            fi
             echo "🚀 Restarting backend with PM2"
             pm2 restart koyal-backend || pm2 start server.js --name koyal-backend
 
           elif [ "$BRANCH" = "koyal-demo" ]; then
             echo "🔨 Building frontend for demo at /var/www/demo-koyal/Client"
             cd /var/www/demo-koyal/Client
+            git pull origin koyal-demo
             npm install
             npm run build
 
           elif [ "$BRANCH" = "koyal-charcha" ]; then
             echo "🔨 Building frontend for charcha at /var/www/charcha/Client"
             cd /var/www/charcha/Client
+            git pull origin koyal-charcha
             npm install
             npm run build
 
